# Generated by Django 5.2 on 2025-04-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasefapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderdetailid', models.AutoField(db_column='OrderDetailID', primary_key=True, serialize=False)),
                ('unitprice', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=19)),
                ('quantity', models.SmallIntegerField(db_column='Quantity')),
                ('discount', models.DecimalField(db_column='Discount', decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'order details',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
